// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.hass_group */
export type HassGroupId = string & { __brand: 'HassGroupId' };

/** Represents the table public.hass_group */
export default interface HassGroupTable {
  id: ColumnType<HassGroupId, HassGroupId | undefined, HassGroupId>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type HassGroup = Selectable<HassGroupTable>;

export type NewHassGroup = Insertable<HassGroupTable>;

export type HassGroupUpdate = Updateable<HassGroupTable>;
