// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.hass_card */
export type HassCardId = number & { __brand: 'HassCardId' };

/** Represents the table public.hass_card */
export default interface HassCardTable {
  id: ColumnType<HassCardId, HassCardId | undefined, HassCardId>;

  type: ColumnType<string, string, string>;

  entityId: ColumnType<string, string, string>;

  icon: ColumnType<string | null, string | null, string | null>;

  iconActive: ColumnType<string | null, string | null, string | null>;

  lock: ColumnType<boolean | null, boolean | null, boolean | null>;

  name: ColumnType<string | null, string | null, string | null>;

  state: ColumnType<string | null, string | null, string | null>;

  service: ColumnType<unknown | null, unknown | null, unknown | null>;

  stateOptions: ColumnType<unknown | null, unknown | null, unknown | null>;

  trackInSidebar: ColumnType<boolean | null, boolean | null, boolean | null>;
}

export type HassCard = Selectable<HassCardTable>;

export type NewHassCard = Insertable<HassCardTable>;

export type HassCardUpdate = Updateable<HassCardTable>;
