// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as HassCardTable } from './HassCard';
import type { default as KyselyMigrationTable } from './KyselyMigration';
import type { default as KyselyMigrationLockTable } from './KyselyMigrationLock';
import type { default as HassGroupTable } from './HassGroup';

export default interface PublicSchema {
  hass_card: HassCardTable;

  kysely_migration: KyselyMigrationTable;

  kysely_migration_lock: KyselyMigrationLockTable;

  hass_group: HassGroupTable;
}
