// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum auth.aal_level */
enum AalLevel {
  aal1 = 'aal1',
  aal2 = 'aal2',
  aal3 = 'aal3',
};

export default AalLevel;
