// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum auth.code_challenge_method */
enum CodeChallengeMethod {
  s256 = 's256',
  plain = 'plain',
};

export default CodeChallengeMethod;
