// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum auth.factor_status */
enum FactorStatus {
  unverified = 'unverified',
  verified = 'verified',
};

export default FactorStatus;
