// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum auth.factor_type */
enum FactorType {
  totp = 'totp',
  webauthn = 'webauthn',
  phone = 'phone',
};

export default FactorType;
