// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for auth.identities */
export type IdentitiesId = string & { __brand: 'IdentitiesId' };

/**
 * Represents the table auth.identities
 * Auth: Stores identities associated to a user.
 */
export default interface IdentitiesTable {
  id: ColumnType<IdentitiesId, IdentitiesId | undefined, IdentitiesId>;

  provider_id: ColumnType<string, string, string>;

  user_id: ColumnType<UsersId, UsersId, UsersId>;

  identity_data: ColumnType<unknown, unknown, unknown>;

  provider: ColumnType<string, string, string>;

  last_sign_in_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  created_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  updated_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  /** Auth: Email is a generated column that references the optional email property in the identity_data */
  email: ColumnType<string | null, never, never>;
}

export type Identities = Selectable<IdentitiesTable>;

export type NewIdentities = Insertable<IdentitiesTable>;

export type IdentitiesUpdate = Updateable<IdentitiesTable>;
