// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { SessionsId } from './Sessions';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for auth.mfa_amr_claims */
export type MfaAmrClaimsId = string & { __brand: 'MfaAmrClaimsId' };

/**
 * Represents the table auth.mfa_amr_claims
 * auth: stores authenticator method reference claims for multi factor authentication
 */
export default interface MfaAmrClaimsTable {
  id: ColumnType<MfaAmrClaimsId, MfaAmrClaimsId, MfaAmrClaimsId>;

  session_id: ColumnType<SessionsId, SessionsId, SessionsId>;

  created_at: ColumnType<Date, Date | string, Date | string>;

  updated_at: ColumnType<Date, Date | string, Date | string>;

  authentication_method: ColumnType<string, string, string>;
}

export type MfaAmrClaims = Selectable<MfaAmrClaimsTable>;

export type NewMfaAmrClaims = Insertable<MfaAmrClaimsTable>;

export type MfaAmrClaimsUpdate = Updateable<MfaAmrClaimsTable>;
