// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { MfaFactorsId } from './MfaFactors';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for auth.mfa_challenges */
export type MfaChallengesId = string & { __brand: 'MfaChallengesId' };

/**
 * Represents the table auth.mfa_challenges
 * auth: stores metadata about challenge requests made
 */
export default interface MfaChallengesTable {
  id: ColumnType<MfaChallengesId, MfaChallengesId, MfaChallengesId>;

  factor_id: ColumnType<MfaFactorsId, MfaFactorsId, MfaFactorsId>;

  created_at: ColumnType<Date, Date | string, Date | string>;

  verified_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  ip_address: ColumnType<string, string, string>;

  otp_code: ColumnType<string | null, string | null, string | null>;

  web_authn_session_data: ColumnType<unknown | null, unknown | null, unknown | null>;
}

export type MfaChallenges = Selectable<MfaChallengesTable>;

export type NewMfaChallenges = Insertable<MfaChallengesTable>;

export type MfaChallengesUpdate = Updateable<MfaChallengesTable>;
