// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';
import type { default as FactorType } from './FactorType';
import type { default as FactorStatus } from './FactorStatus';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for auth.mfa_factors */
export type MfaFactorsId = string & { __brand: 'MfaFactorsId' };

/**
 * Represents the table auth.mfa_factors
 * auth: stores metadata about factors
 */
export default interface MfaFactorsTable {
  id: ColumnType<MfaFactorsId, MfaFactorsId, MfaFactorsId>;

  user_id: ColumnType<UsersId, UsersId, UsersId>;

  friendly_name: ColumnType<string | null, string | null, string | null>;

  factor_type: ColumnType<FactorType, FactorType, FactorType>;

  status: ColumnType<FactorStatus, FactorStatus, FactorStatus>;

  created_at: ColumnType<Date, Date | string, Date | string>;

  updated_at: ColumnType<Date, Date | string, Date | string>;

  secret: ColumnType<string | null, string | null, string | null>;

  phone: ColumnType<string | null, string | null, string | null>;

  last_challenged_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  web_authn_credential: ColumnType<unknown | null, unknown | null, unknown | null>;

  web_authn_aaguid: ColumnType<string | null, string | null, string | null>;
}

export type MfaFactors = Selectable<MfaFactorsTable>;

export type NewMfaFactors = Insertable<MfaFactorsTable>;

export type MfaFactorsUpdate = Updateable<MfaFactorsTable>;
