// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum auth.one_time_token_type */
enum OneTimeTokenType {
  confirmation_token = 'confirmation_token',
  reauthentication_token = 'reauthentication_token',
  recovery_token = 'recovery_token',
  email_change_token_new = 'email_change_token_new',
  email_change_token_current = 'email_change_token_current',
  phone_change_token = 'phone_change_token',
};

export default OneTimeTokenType;
