// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';
import type { default as OneTimeTokenType } from './OneTimeTokenType';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for auth.one_time_tokens */
export type OneTimeTokensId = string & { __brand: 'OneTimeTokensId' };

/** Represents the table auth.one_time_tokens */
export default interface OneTimeTokensTable {
  id: ColumnType<OneTimeTokensId, OneTimeTokensId, OneTimeTokensId>;

  user_id: ColumnType<UsersId, UsersId, UsersId>;

  token_type: ColumnType<OneTimeTokenType, OneTimeTokenType, OneTimeTokenType>;

  token_hash: ColumnType<string, string, string>;

  relates_to: ColumnType<string, string, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type OneTimeTokens = Selectable<OneTimeTokensTable>;

export type NewOneTimeTokens = Insertable<OneTimeTokensTable>;

export type OneTimeTokensUpdate = Updateable<OneTimeTokensTable>;
