// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { SessionsId } from './Sessions';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for auth.refresh_tokens */
export type RefreshTokensId = string & { __brand: 'RefreshTokensId' };

/**
 * Represents the table auth.refresh_tokens
 * Auth: Store of tokens used to refresh JWT tokens once they expire.
 */
export default interface RefreshTokensTable {
  id: ColumnType<RefreshTokensId, RefreshTokensId | undefined, RefreshTokensId>;

  instance_id: ColumnType<string | null, string | null, string | null>;

  token: ColumnType<string | null, string | null, string | null>;

  user_id: ColumnType<string | null, string | null, string | null>;

  revoked: ColumnType<boolean | null, boolean | null, boolean | null>;

  created_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  updated_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  parent: ColumnType<string | null, string | null, string | null>;

  session_id: ColumnType<SessionsId | null, SessionsId | null, SessionsId | null>;
}

export type RefreshTokens = Selectable<RefreshTokensTable>;

export type NewRefreshTokens = Insertable<RefreshTokensTable>;

export type RefreshTokensUpdate = Updateable<RefreshTokensTable>;
