// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { SsoProvidersId } from './SsoProviders';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for auth.saml_providers */
export type SamlProvidersId = string & { __brand: 'SamlProvidersId' };

/**
 * Represents the table auth.saml_providers
 * Auth: Manages SAML Identity Provider connections.
 */
export default interface SamlProvidersTable {
  id: ColumnType<SamlProvidersId, SamlProvidersId, SamlProvidersId>;

  sso_provider_id: ColumnType<SsoProvidersId, SsoProvidersId, SsoProvidersId>;

  entity_id: ColumnType<string, string, string>;

  metadata_xml: ColumnType<string, string, string>;

  metadata_url: ColumnType<string | null, string | null, string | null>;

  attribute_mapping: ColumnType<unknown | null, unknown | null, unknown | null>;

  created_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  updated_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  name_id_format: ColumnType<string | null, string | null, string | null>;
}

export type SamlProviders = Selectable<SamlProvidersTable>;

export type NewSamlProviders = Insertable<SamlProvidersTable>;

export type SamlProvidersUpdate = Updateable<SamlProvidersTable>;
