// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { SsoProvidersId } from './SsoProviders';
import type { FlowStateId } from './FlowState';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for auth.saml_relay_states */
export type SamlRelayStatesId = string & { __brand: 'SamlRelayStatesId' };

/**
 * Represents the table auth.saml_relay_states
 * Auth: Contains SAML Relay State information for each Service Provider initiated login.
 */
export default interface SamlRelayStatesTable {
  id: ColumnType<SamlRelayStatesId, SamlRelayStatesId, SamlRelayStatesId>;

  sso_provider_id: ColumnType<SsoProvidersId, SsoProvidersId, SsoProvidersId>;

  request_id: ColumnType<string, string, string>;

  for_email: ColumnType<string | null, string | null, string | null>;

  redirect_to: ColumnType<string | null, string | null, string | null>;

  created_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  updated_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  flow_state_id: ColumnType<FlowStateId | null, FlowStateId | null, FlowStateId | null>;
}

export type SamlRelayStates = Selectable<SamlRelayStatesTable>;

export type NewSamlRelayStates = Insertable<SamlRelayStatesTable>;

export type SamlRelayStatesUpdate = Updateable<SamlRelayStatesTable>;
