// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';
import type { default as AalLevel } from './AalLevel';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for auth.sessions */
export type SessionsId = string & { __brand: 'SessionsId' };

/**
 * Represents the table auth.sessions
 * Auth: Stores session data associated to a user.
 */
export default interface SessionsTable {
  id: ColumnType<SessionsId, SessionsId, SessionsId>;

  user_id: ColumnType<UsersId, UsersId, UsersId>;

  created_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  updated_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  factor_id: ColumnType<string | null, string | null, string | null>;

  aal: ColumnType<AalLevel | null, AalLevel | null, AalLevel | null>;

  /** Auth: Not after is a nullable column that contains a timestamp after which the session should be regarded as expired. */
  not_after: ColumnType<Date | null, Date | string | null, Date | string | null>;

  refreshed_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  user_agent: ColumnType<string | null, string | null, string | null>;

  ip: ColumnType<string | null, string | null, string | null>;

  tag: ColumnType<string | null, string | null, string | null>;
}

export type Sessions = Selectable<SessionsTable>;

export type NewSessions = Insertable<SessionsTable>;

export type SessionsUpdate = Updateable<SessionsTable>;
