// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { SsoProvidersId } from './SsoProviders';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for auth.sso_domains */
export type SsoDomainsId = string & { __brand: 'SsoDomainsId' };

/**
 * Represents the table auth.sso_domains
 * Auth: Manages SSO email address domain mapping to an SSO Identity Provider.
 */
export default interface SsoDomainsTable {
  id: ColumnType<SsoDomainsId, SsoDomainsId, SsoDomainsId>;

  sso_provider_id: ColumnType<SsoProvidersId, SsoProvidersId, SsoProvidersId>;

  domain: ColumnType<string, string, string>;

  created_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  updated_at: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type SsoDomains = Selectable<SsoDomainsTable>;

export type NewSsoDomains = Insertable<SsoDomainsTable>;

export type SsoDomainsUpdate = Updateable<SsoDomainsTable>;
