// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum realtime.action */
enum Action {
  INSERT = 'INSERT',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  TRUNCATE = 'TRUNCATE',
  ERROR = 'ERROR',
};

export default Action;
