// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum realtime.equality_op */
enum EqualityOp {
  eq = 'eq',
  neq = 'neq',
  lt = 'lt',
  lte = 'lte',
  gt = 'gt',
  gte = 'gte',
  'in' = 'in',
};

export default EqualityOp;
