// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table realtime.messages */
export default interface MessagesTable {
  topic: ColumnType<string, string, string>;

  extension: ColumnType<string, string, string>;

  payload: ColumnType<unknown | null, unknown | null, unknown | null>;

  event: ColumnType<string | null, string | null, string | null>;

  private: ColumnType<boolean | null, boolean | null, boolean | null>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  inserted_at: ColumnType<Date, Date | string | undefined, Date | string>;

  id: ColumnType<string, string | undefined, string>;
}

export type Messages = Selectable<MessagesTable>;

export type NewMessages = Insertable<MessagesTable>;

export type MessagesUpdate = Updateable<MessagesTable>;
