// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as SubscriptionTable } from './Subscription';
import type { default as SchemaMigrationsTable } from './SchemaMigrations';
import type { default as MessagesTable } from './Messages';
import type { default as UserDefinedFilterTable } from './UserDefinedFilter';
import type { default as WalColumnTable } from './WalColumn';
import type { default as WalRlsTable } from './WalRls';

export default interface RealtimeSchema {
  subscription: SubscriptionTable;

  schema_migrations: SchemaMigrationsTable;

  messages: MessagesTable;

  user_defined_filter: UserDefinedFilterTable;

  wal_column: WalColumnTable;

  wal_rls: WalRlsTable;
}
