// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for realtime.schema_migrations */
export type SchemaMigrationsVersion = string & { __brand: 'SchemaMigrationsVersion' };

/** Represents the table realtime.schema_migrations */
export default interface SchemaMigrationsTable {
  version: ColumnType<SchemaMigrationsVersion, SchemaMigrationsVersion, SchemaMigrationsVersion>;

  inserted_at: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type SchemaMigrations = Selectable<SchemaMigrationsTable>;

export type NewSchemaMigrations = Insertable<SchemaMigrationsTable>;

export type SchemaMigrationsUpdate = Updateable<SchemaMigrationsTable>;
