// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as EqualityOp } from './EqualityOp';
import type { ColumnType, Selectable } from 'kysely';

/** Represents the compositeType realtime.user_defined_filter */
export default interface UserDefinedFilterTable {
  column_name: ColumnType<string | null, never, never>;

  op: ColumnType<EqualityOp | null, never, never>;

  value: ColumnType<string | null, never, never>;
}

export type UserDefinedFilter = Selectable<UserDefinedFilterTable>;
