// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable } from 'kysely';

/** Represents the compositeType realtime.wal_rls */
export default interface WalRlsTable {
  wal: ColumnType<unknown | null, never, never>;

  is_rls_enabled: ColumnType<boolean | null, never, never>;

  subscription_ids: ColumnType<string[] | null, never, never>;

  errors: ColumnType<string[] | null, never, never>;
}

export type WalRls = Selectable<WalRlsTable>;
