services:
  # === DASHBOARD FRONTEND ===
  dashboard-frontend:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: dashboard-frontend
    ports:
      - "8080:80"
    restart: unless-stopped

  # === DASHBOARD BACKEND ===
  dashboard-backend:
    build:
      context: ./dashboard-server
      dockerfile: Dockerfile
    container_name: dashboard-backend
    ports:
      - "3000:3000"
    restart: unless-stopped
