services:
  dashboard:
    build:
      context: .
      dockerfile: apps/dashboard/Dockerfile
    ports:
      - '8080:80'
    restart: unless-stopped

  dashboard-server:
    build:
      context: .
      dockerfile: apps/dashboard-server/Dockerfile
    env_file:
      - .env
    environment:
      - PORT=3000
    ports:
      - '8081:3000'
    restart: unless-stopped
