// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as DecryptedSecretsTable } from './DecryptedSecrets';

export default interface VaultSchema {
  decrypted_secrets: DecryptedSecretsTable;
}
