// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for storage.buckets */
export type BucketsId = string & { __brand: 'BucketsId' };

/** Represents the table storage.buckets */
export default interface BucketsTable {
  id: ColumnType<BucketsId, BucketsId, BucketsId>;

  name: ColumnType<string, string, string>;

  /** Field is deprecated, use owner_id instead */
  owner: ColumnType<string | null, string | null, string | null>;

  created_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  updated_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  public: ColumnType<boolean | null, boolean | null, boolean | null>;

  avif_autodetection: ColumnType<boolean | null, boolean | null, boolean | null>;

  file_size_limit: ColumnType<string | null, string | null, string | null>;

  allowed_mime_types: ColumnType<string[] | null, string[] | null, string[] | null>;

  owner_id: ColumnType<string | null, string | null, string | null>;
}

export type Buckets = Selectable<BucketsTable>;

export type NewBuckets = Insertable<BucketsTable>;

export type BucketsUpdate = Updateable<BucketsTable>;
