// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { S3MultipartUploadsId } from './S3MultipartUploads';
import type { BucketsId } from './Buckets';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for storage.s3_multipart_uploads_parts */
export type S3MultipartUploadsPartsId = string & { __brand: 'S3MultipartUploadsPartsId' };

/** Represents the table storage.s3_multipart_uploads_parts */
export default interface S3MultipartUploadsPartsTable {
  id: ColumnType<S3MultipartUploadsPartsId, S3MultipartUploadsPartsId | undefined, S3MultipartUploadsPartsId>;

  upload_id: ColumnType<S3MultipartUploadsId, S3MultipartUploadsId, S3MultipartUploadsId>;

  size: ColumnType<string, string | undefined, string>;

  part_number: ColumnType<number, number, number>;

  bucket_id: ColumnType<BucketsId, BucketsId, BucketsId>;

  key: ColumnType<string, string, string>;

  etag: ColumnType<string, string, string>;

  owner_id: ColumnType<string | null, string | null, string | null>;

  version: ColumnType<string, string, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type S3MultipartUploadsParts = Selectable<S3MultipartUploadsPartsTable>;

export type NewS3MultipartUploadsParts = Insertable<S3MultipartUploadsPartsTable>;

export type S3MultipartUploadsPartsUpdate = Updateable<S3MultipartUploadsPartsTable>;
