// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as S3MultipartUploadsPartsTable } from './S3MultipartUploadsParts';
import type { default as BucketsTable } from './Buckets';
import type { default as MigrationsTable } from './Migrations';
import type { default as ObjectsTable } from './Objects';
import type { default as S3MultipartUploadsTable } from './S3MultipartUploads';

export default interface StorageSchema {
  s3_multipart_uploads_parts: S3MultipartUploadsPartsTable;

  buckets: BucketsTable;

  migrations: MigrationsTable;

  objects: ObjectsTable;

  s3_multipart_uploads: S3MultipartUploadsTable;
}
