import { provideIcons } from '@ng-icons/core';
import {
  phosphorLightbulbDuotone,
  phosphorSpeakerHifiDuotone,
} from '@ng-icons/phosphor-icons/duotone';
import {
  phosphorBed,
  phosphorCouch,
  phosphorDesktopTower,
  phosphorForkKnife,
  phosphorKnife,
  phosphorLightbulb,
  phosphorMinus,
  phosphorPause,
  phosphorPencilRuler,
  phosphorPlay,
  phosphorPlus,
  phosphorQuestion,
  phosphorSkipBack,
  phosphorSkipForward,
  phosphorSliders,
  phosphorSpeakerHifi,
  phosphorThermometerCold,
  phosphorThermometerHot,
  phosphorThermometerSimple,
  phosphorToiletPaper,
  phosphorVectorThree,
} from '@ng-icons/phosphor-icons/regular';
import { phosphorLightbulbBold } from '@ng-icons/phosphor-icons/bold';
import { phosphorLightbulbFill } from '@ng-icons/phosphor-icons/fill';

export const appIconProviders = provideIcons({
  lightbulb: phosphorLightbulb,
  lightbulbDuo: phosphorLightbulbDuotone,
  lightbulbBold: phosphorLightbulbBold,
  lightbulbFill: phosphorLightbulbFill,
  speaker: phosphorSpeakerHifi,
  speakerDuo: phosphorSpeakerHifiDuotone,
  sliders: phosphorSliders,
  play: phosphorPlay,
  pause: phosphorPause,
  skipForward: phosphorSkipForward,
  skipBack: phosphorSkipBack,
  thermometer: phosphorThermometerSimple,
  thermometerHot: phosphorThermometerHot,
  thermometerCold: phosphorThermometerCold,
  plus: phosphorPlus,
  minus: phosphorMinus,
  computer: phosphorDesktopTower,
  couch: phosphorCouch,
  toiletPaper: phosphorToiletPaper,
  bed: phosphorBed,
  forkKnife: phosphorForkKnife,
  knife: phosphorKnife,
  pencilRuler: phosphorPencilRuler,
  question: phosphorQuestion,
  vectors: phosphorVectorThree,
});
