name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout Repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Setup pnpm (Recommended Way)
      - uses: pnpm/action-setup@v4
        with:
          version: latest

      # 3️⃣ Setup Node.js with pnpm Caching
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # 4️⃣ Install Dependencies with pnpm
      - run: pnpm install --frozen-lockfile

      # 5️⃣ Set Nx SHAs (Optimize Affected Commands)
      - uses: nrwl/nx-set-shas@v4

      # 6️⃣ Run Nx Affected Commands with pnpm
      - run: pnpm nx affected -t lint test build
