name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout Repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Install Bun
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      # 3️⃣ Upgrade Bun (Ensure Latest Version)
      - name: Upgrade Bun
        run: bun upgrade

      # 4️⃣ Clear Bun Cache to Fix SIGBUS
      - name: Clean Bun Cache
        run: rm -rf ~/.bun/install/cache

      # 5️⃣ Install Dependencies with Bun (Disable Postinstall)
      - run: BUN_NO_POSTINSTALL=1 bun install --frozen-lockfile

      # 6️⃣ Set Nx SHAs (Optimize Affected Commands)
      - uses: nrwl/nx-set-shas@v4

      # 7️⃣ Run Nx Affected Commands with Bun
      - run: bunx nx affected -t lint test build
