name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout Repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Setup Node.js & Enable pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        run: corepack enable

      # 3️⃣ Install Dependencies with pnpm
      - run: pnpm install --frozen-lockfile

      # 4️⃣ Set Nx SHAs (Optimize Affected Commands)
      - uses: nrwl/nx-set-shas@v4

      # 5️⃣ Run Nx Affected Commands with pnpm
      - run: pnpm nx affected -t lint test build
